#!/usr/bin/env bash
# bump-build-stamp.sh — increment the Linux build number and rewrite the stamp
# header, on the WORKSTATION, so it can be committed and pulled by the rig.
#
#   platforms/linux/bump-build-stamp.sh              # bump + write
#   platforms/linux/bump-build-stamp.sh --commit     # …and git commit it
#   platforms/linux/bump-build-stamp.sh --show       # print current stamp, change nothing
#
# ⚠️ WHY THIS EXISTS (2026-09-09, SP-124): `deploy-to-rig.sh` bundles the counter
# increment with shipping the tree over SSH. When the rig is updated by
# `git pull` instead — which is the better route, because it puts the rig on a
# KNOWN COMMIT rather than an ad-hoc tree — nothing bumps the number, so the rig
# builds new code that still REPORTS THE OLD BUILD. That happened: build 33 was
# a day stale and a live pass was nearly run against it.
#
# ⚠️ THE RIG IS READ-ONLY FOR SOURCE. Editing the stamp there destroys checksum
# equivalence between the two trees, so you can no longer prove which code the
# rig is running. Bump HERE, commit, push, pull.
#
# ⚠️ Shares the counter file with deploy-to-rig.sh so the two routes cannot
# collide or reuse a number.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STAMP_HEADER="${REPO_ROOT}/platforms/linux/generated/ScriviBuildStamp.hpp"
COUNTER_FILE="${HOME}/.scrivi-rig-build-number"

DO_COMMIT=0
for arg in "$@"; do
    case "$arg" in
        --commit) DO_COMMIT=1 ;;
        --show)
            if [ -f "$STAMP_HEADER" ]; then cat "$STAMP_HEADER"; else
                echo "no stamp header at ${STAMP_HEADER}" >&2; exit 1; fi
            exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

# --- increment the shared counter -------------------------------------------
BUILD_NO=0
if [ -f "$COUNTER_FILE" ]; then
    BUILD_NO="$(cat "$COUNTER_FILE" 2>/dev/null || echo 0)"
fi
# Guard a truncated or hand-edited counter rather than failing over it.
case "$BUILD_NO" in
    ''|*[!0-9]*) BUILD_NO=0 ;;
esac
BUILD_NO=$((BUILD_NO + 1))
echo "$BUILD_NO" > "$COUNTER_FILE"

mkdir -p "$(dirname "$STAMP_HEADER")"
cat > "$STAMP_HEADER" <<STAMPEOF
#pragma once
// ⚠️ GENERATED BY platforms/linux/bump-build-stamp.sh — do not edit.
#define SCRIVI_BUILD_NUMBER ${BUILD_NO}
#define SCRIVI_BUILD_STAMP "$(date -u '+%Y-%m-%d %H:%M:%S') UTC"
STAMPEOF

echo "==> Build number: ${BUILD_NO}"
cat "$STAMP_HEADER"

if [ "$DO_COMMIT" -eq 1 ]; then
    cd "$REPO_ROOT"
    git add "$STAMP_HEADER"
    git commit -m "Linux build stamp ${BUILD_NO}"
    echo "==> Committed. Now: git push origin main"
    echo "    Then on the rig: git pull origin main && \\"
    echo "      cmake --build build-native --target scrivi_linux -j 4 && \\"
    echo "      ./build-native/platforms/linux/scrivi_linux --version"
else
    echo "==> NOT committed. To ship it to the rig:"
    echo "    git add ${STAMP_HEADER#"$REPO_ROOT"/} && git commit && git push origin main"
fi
