#!/usr/bin/env bash
# deploy-to-rig.sh — push the working tree to the Linux rig, build it there, and
# CONFIRM the build stamp moved.
#
#   platforms/linux/deploy-to-rig.sh            # deploy + build + verify
#   platforms/linux/deploy-to-rig.sh --test     # …and run ctest + the smokes
#   platforms/linux/deploy-to-rig.sh --run      # …and launch the app on the rig
#
# Host defaults to `oathkeeper`; override with SCRIVI_RIG. The remote path
# defaults to ~/Dev/Scrivi; override with SCRIVI_RIG_PATH.
#
# ⚠️ WHY THIS EXISTS: on 2026-08-30 a live pass was nearly run against a DAY-OLD
# binary that predated an entire sprint. Pushing source does NOT rebuild, and a
# green build on the workstation says NOTHING about what is installed on the rig.
# ⚠️ This script always ends by printing the stamp, so "did my change land?" is
# answered every time rather than assumed.
#
# ⚠️ It ships the WORKING TREE, including UNCOMMITTED and UNTRACKED files —
# deliberately, because that is what you are testing. `git ls-files` alone
# silently omits work in progress, and the configure then fails on missing
# sources (which is exactly what happened the first time).
set -euo pipefail

RIG="${SCRIVI_RIG:-oathkeeper}"
RIG_PATH="${SCRIVI_RIG_PATH:-Dev/Scrivi}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

DO_TEST=0
DO_RUN=0
for arg in "$@"; do
    case "$arg" in
        --test) DO_TEST=1 ;;
        --run)  DO_RUN=1 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

echo "==> Rig: ${RIG}:~/${RIG_PATH}"

# --- reachability -----------------------------------------------------------
# ⚠️ The rig SLEEPS. A failed connection here usually means asleep, not broken.
if ! ssh -o BatchMode=yes -o ConnectTimeout=8 "$RIG" true 2>/dev/null; then
    echo "ERROR: cannot reach ${RIG} over SSH." >&2
    echo "       The rig may simply be ASLEEP — wake it and try again." >&2
    echo "       (Key auth needs a ~/.ssh/config entry naming the dedicated key;" >&2
    echo "        see docs/Scrivi_Linux_Rig_Setup_v0_1.md §2.1.)" >&2
    exit 1
fi

# --- ⚠️ increment the build number BEFORE packaging -------------------------
#
# ⚠️ The counter belongs to the PUSH, not to the compile. Two CMake-side attempts
# to generate it during the build both failed (see platforms/linux/CMakeLists.txt)
# — Ninja either noticed the change one build late, or never re-ran the step at
# all and froze the number at 1.
#
# ✅ Doing it here makes the number change exactly when the SOURCE does, which is
# the question being asked: "is the rig running what I just pushed?"
#
# ⚠️ The counter lives OUTSIDE the repo (~/.scrivi-rig-build-number) so it is
# never committed and never conflicts. The generated header IS committed as a
# fallback, but its value is only meaningful right after a deploy.
COUNTER_FILE="${HOME}/.scrivi-rig-build-number"
BUILD_NO=0
if [ -f "$COUNTER_FILE" ]; then
    BUILD_NO="$(cat "$COUNTER_FILE" 2>/dev/null || echo 0)"
fi
# Guard a truncated or hand-edited counter rather than failing the deploy over it.
case "$BUILD_NO" in
    ''|*[!0-9]*) BUILD_NO=0 ;;
esac
BUILD_NO=$((BUILD_NO + 1))
echo "$BUILD_NO" > "$COUNTER_FILE"

STAMP_HEADER="${REPO_ROOT}/platforms/linux/generated/ScriviBuildStamp.hpp"
cat > "$STAMP_HEADER" <<STAMPEOF
#pragma once
// ⚠️ GENERATED BY platforms/linux/deploy-to-rig.sh — do not edit.
#define SCRIVI_BUILD_NUMBER ${BUILD_NO}
#define SCRIVI_BUILD_STAMP "$(date -u '+%Y-%m-%d %H:%M:%S') UTC"
STAMPEOF
echo "==> Build number: ${BUILD_NO}"

# --- package the working tree ----------------------------------------------
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
{ git ls-files; git ls-files --others --exclude-standard; } | sort -u > "$STAGE/filelist"
COUNT=$(wc -l < "$STAGE/filelist" | tr -d ' ')
echo "==> Packaging ${COUNT} files (tracked + untracked, excluding .gitignore'd)…"
tar -czf "$STAGE/src.tgz" -T "$STAGE/filelist"

# --- ship + unpack ----------------------------------------------------------
echo "==> Copying to ${RIG}…"
scp -q "$STAGE/src.tgz" "${RIG}:/tmp/scrivi-src.tgz"

# ⚠️ macOS `tar` regenerates AppleDouble `._*` files from extended attributes
# even when they were deleted before archiving, so they are stripped ON THE RIG.
ssh "$RIG" "set -e
    mkdir -p ~/${RIG_PATH}
    cd ~/${RIG_PATH}
    tar -xzf /tmp/scrivi-src.tgz 2>/dev/null || true
    rm -f /tmp/scrivi-src.tgz
    find . -name '._*' -delete 2>/dev/null || true"

# --- configure (only if needed) + build ------------------------------------
# ⚠️ A CMake build tree does NOT survive being moved — CMakeCache.txt bakes
# absolute paths. Configuring only when the cache is absent keeps rebuilds fast
# while still handling a fresh clone.
echo "==> Building natively on ${RIG}…"
ssh "$RIG" "set -e
    cd ~/${RIG_PATH}
    if [ ! -f build-native/CMakeCache.txt ]; then
        cmake -S . -B build-native -G Ninja \
              -DSCRIVI_BUILD_LINUX=ON -DSCRIVI_BUILD_TESTS=ON \
              -DCMAKE_BUILD_TYPE=Release
    fi
    cmake --build build-native --parallel"

# --- ⚠️ THE POINT OF THE SCRIPT --------------------------------------------
# ⚠️ The build NUMBER is what makes this check trivial: it either matches or it
# does not, with no clock arithmetic. It increments once per build on the rig.
echo
VERSION_LINE="$(ssh "$RIG" "~/${RIG_PATH}/build-native/platforms/linux/scrivi_linux --version")"
DEPLOYED_NO="$(printf '%s' "$VERSION_LINE" | sed -n 's/.*build \([0-9]*\).*/\1/p')"
echo "==> Deployed:  ${VERSION_LINE}"

# ⚠️ Verify the binary actually carries the number we just shipped. If it does
# not, the build silently did not pick up the new source — which is the exact
# failure this whole mechanism exists to catch.
if [ "$DEPLOYED_NO" != "$BUILD_NO" ]; then
    echo
    echo "ERROR: expected build ${BUILD_NO} but the rig reports ${DEPLOYED_NO:-none}." >&2
    echo "       The binary does NOT match the source just pushed." >&2
    exit 1
fi
echo
echo "    ┌────────────────────────────────────────────────┐"
printf  "    │  Check the app reports:  BUILD %-15s │\n" "${BUILD_NO:-?}"
echo "    └────────────────────────────────────────────────┘"
echo "    In the app: Help ▸ About Scrivi."
echo "    ⚠️  A DIFFERENT number means you are running an older binary."

# --- optional: tests --------------------------------------------------------
if [ "$DO_TEST" = "1" ]; then
    echo
    echo "==> ctest (non-root) + Linux smokes…"
    ssh "$RIG" "set -e
        cd ~/${RIG_PATH}
        ctest --test-dir build-native 2>&1 | tail -3
        f=0; p=0
        for sh in platforms/linux/tests/*.sh; do
            n=\$(basename \"\$sh\" .sh)
            b=\"./build-native/platforms/linux/scrivi_linux_\${n}\"
            [ -x \"\$b\" ] || continue
            if bash \"\$sh\" \"\$b\" >/dev/null 2>&1; then p=\$((p+1)); else echo \"FAIL \$n\"; f=\$((f+1)); fi
        done
        echo \"smokes: \$p passed, \$f failed\""
fi

# --- optional: launch -------------------------------------------------------
if [ "$DO_RUN" = "1" ]; then
    echo
    # ⚠️ The app needs a REAL display, which SSH does not have. Launching it from
    # here would either fail or push a window onto someone else's session.
    echo "==> To run it, open a terminal INSIDE the RDP session and use:"
    echo "        ~/${RIG_PATH}/build-native/platforms/linux/scrivi_linux"
    echo "    …or the Scrivi shortcut on the rig's Desktop."
    echo
    echo "    ⚠️  It cannot be launched over SSH: there is no DISPLAY, and forcing"
    echo "        one would push a window onto the RDP session rather than test it."
fi

echo
echo "==> Done."
